name: foxy_dart
version: 3.0.0
description: A simple command-line application.
repository: https://github.com/Dark-Fox-PL/foxy-dart
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  http: ^0.13.4
  nyxx: ^3.2.7
  nyxx_interactions: ^3.3.0
  path: ^1.8.0
  postgresql2: ^1.0.2
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
